apiVersion: nfs.rook.io/v1alpha1
kind: NFSServer
metadata:
  name: nfs-vol
  namespace: rook
spec:
  replicas: 1
  exports:
    - name: nfs-share
      server:
        accessMode: ReadWrite
        squash: none
      persistentVolumeClaim:
        claimName: googlePD-claim
  # A key/value list of annotations
  annotations:
  #  key: value