runmode: debug               # 开发模式, debug, release, test
addr: :6663                  # HTTP绑定端口
name: apiserver              # API Server的名字
url: http://127.0.0.1:6663   # pingServer函数请求的API服务器的ip:port
max_ping_count: 10
gromlog: true
log:
  writers: file,stoud
  logger_level: DEBUG
  logger_file: log/apiserver.log
  log_format_text: false
  rollingPolicy: size
  log_rorate_date: 1
  log_rorate_size: 1024
  log_backup_count: 7
db:
  name: db_apiserver
  addr:  192.168.14.137:3306
  username: root
  password: gGSWJP0oK4Q6XPwl@
dockder_db:
  name: db_apiserver
  addr:  127.0.0.1:3306
  username: root
  password: root